package com.example.recme.ai.whisper

/**
 * Supported language definitions and configurable language whitelist for Whisper ASR (all 99 languages).
 */
data class SupportedLanguage(
    val code: String,
    val name: String,
    val nativeName: String
)

object WhisperLanguageConfig {

    val DEFAULT_LANGUAGES = listOf("af", "en", "de")

    val ALL_SUPPORTED_LANGUAGES = listOf(
        SupportedLanguage("af", "Afrikaans", "Afrikaans"),
        SupportedLanguage("en", "English", "English"),
        SupportedLanguage("de", "German", "Deutsch"),
        SupportedLanguage("nl", "Dutch", "Nederlands"),
        SupportedLanguage("fr", "French", "Français"),
        SupportedLanguage("es", "Spanish", "Español"),
        SupportedLanguage("it", "Italian", "Italiano"),
        SupportedLanguage("pt", "Portuguese", "Português"),
        SupportedLanguage("sv", "Swedish", "Svenska"),
        SupportedLanguage("no", "Norwegian", "Norsk"),
        SupportedLanguage("da", "Danish", "Dansk"),
        SupportedLanguage("fi", "Finnish", "Suomi"),
        SupportedLanguage("pl", "Polish", "Polski"),
        SupportedLanguage("ru", "Russian", "Русский"),
        SupportedLanguage("uk", "Ukrainian", "Українська"),
        SupportedLanguage("cs", "Czech", "Čeština"),
        SupportedLanguage("sk", "Slovak", "Slovenčina"),
        SupportedLanguage("hu", "Hungarian", "Magyar"),
        SupportedLanguage("ro", "Romanian", "Română"),
        SupportedLanguage("bg", "Bulgarian", "Български"),
        SupportedLanguage("el", "Greek", "Ελληνικά"),
        SupportedLanguage("tr", "Turkish", "Türkçe"),
        SupportedLanguage("ar", "Arabic", "العربية"),
        SupportedLanguage("he", "Hebrew", "עברית"),
        SupportedLanguage("hi", "Hindi", "हिन्दी"),
        SupportedLanguage("ur", "Urdu", "اردو"),
        SupportedLanguage("fa", "Persian", "فارسی"),
        SupportedLanguage("zh", "Chinese", "中文"),
        SupportedLanguage("ja", "Japanese", "日本語"),
        SupportedLanguage("ko", "Korean", "한국어"),
        SupportedLanguage("vi", "Vietnamese", "Tiếng Việt"),
        SupportedLanguage("id", "Indonesian", "Bahasa Indonesia"),
        SupportedLanguage("ms", "Malay", "Bahasa Melayu"),
        SupportedLanguage("th", "Thai", "ไทย"),
        SupportedLanguage("sw", "Swahili", "Kiswahili"),
        SupportedLanguage("sq", "Albanian", "Shqip"),
        SupportedLanguage("am", "Amharic", "አማርኛ"),
        SupportedLanguage("hy", "Armenian", "Հայերեն"),
        SupportedLanguage("as", "Assamese", "অসমীয়া"),
        SupportedLanguage("az", "Azerbaijani", "Azərbaycan"),
        SupportedLanguage("ba", "Bashkir", "Башҡортса"),
        SupportedLanguage("eu", "Basque", "Euskara"),
        SupportedLanguage("be", "Belarusian", "Беларуская"),
        SupportedLanguage("bn", "Bengali", "বাংলা"),
        SupportedLanguage("bs", "Bosnian", "Bosanski"),
        SupportedLanguage("br", "Breton", "Brezhoneg"),
        SupportedLanguage("my", "Burmese", "မြန်မာစာ"),
        SupportedLanguage("ca", "Catalan", "Català"),
        SupportedLanguage("hr", "Croatian", "Hrvatski"),
        SupportedLanguage("et", "Estonian", "Eesti"),
        SupportedLanguage("fo", "Faroese", "Føroyskt"),
        SupportedLanguage("gl", "Galician", "Galego"),
        SupportedLanguage("ka", "Georgian", "ქართული"),
        SupportedLanguage("gu", "Gujarati", "ગુજરાતી"),
        SupportedLanguage("ht", "Haitian Creole", "Kreyòl Ayisyen"),
        SupportedLanguage("ha", "Hausa", "Hausa"),
        SupportedLanguage("haw", "Hawaiian", "ʻŌlelo Hawaiʻi"),
        SupportedLanguage("is", "Icelandic", "Íslenska"),
        SupportedLanguage("jw", "Javanese", "Basa Jawa"),
        SupportedLanguage("kn", "Kannada", "ಕನ್ನಡ"),
        SupportedLanguage("kk", "Kazakh", "Қазақша"),
        SupportedLanguage("km", "Khmer", "ភាសាខ្មែរ"),
        SupportedLanguage("lo", "Lao", "ພາສາລາວ"),
        SupportedLanguage("la", "Latin", "Latina"),
        SupportedLanguage("lv", "Latvian", "Latviešu"),
        SupportedLanguage("ln", "Lingala", "Lingála"),
        SupportedLanguage("lt", "Lithuanian", "Lietuvių"),
        SupportedLanguage("lb", "Luxembourgish", "Lëtzebuergesch"),
        SupportedLanguage("mk", "Macedonian", "Македонски"),
        SupportedLanguage("mg", "Malagasy", "Malagasy"),
        SupportedLanguage("ml", "Malayalam", "മലയാളം"),
        SupportedLanguage("mt", "Maltese", "Malti"),
        SupportedLanguage("mi", "Maori", "Te Reo Māori"),
        SupportedLanguage("mr", "Marathi", "मराठी"),
        SupportedLanguage("mn", "Mongolian", "Монгол"),
        SupportedLanguage("ne", "Nepali", "नेपाली"),
        SupportedLanguage("nn", "Nynorsk", "Nynorsk"),
        SupportedLanguage("oc", "Occitan", "Occitan"),
        SupportedLanguage("ps", "Pashto", "پښتو"),
        SupportedLanguage("pa", "Punjabi", "ਪੰਜਾਬੀ"),
        SupportedLanguage("sa", "Sanskrit", "संस्कृतम्"),
        SupportedLanguage("sr", "Serbian", "Српски"),
        SupportedLanguage("sn", "Shona", "chiShona"),
        SupportedLanguage("sd", "Sindhi", "سنڌي"),
        SupportedLanguage("si", "Sinhala", "සිංහල"),
        SupportedLanguage("sl", "Slovenian", "Slovenščina"),
        SupportedLanguage("so", "Somali", "Soomaaliga"),
        SupportedLanguage("su", "Sundanese", "Basa Sunda"),
        SupportedLanguage("tl", "Tagalog", "Tagalog"),
        SupportedLanguage("tg", "Tajik", "Тоҷикӣ"),
        SupportedLanguage("ta", "Tamil", "தமிழ்"),
        SupportedLanguage("tt", "Tatar", "Татарча"),
        SupportedLanguage("te", "Telugu", "తెలుగు"),
        SupportedLanguage("bo", "Tibetan", "བོད་སྐད་"),
        SupportedLanguage("tk", "Turkmen", "Türkmençe"),
        SupportedLanguage("uz", "Uzbek", "Oʻzbekcha"),
        SupportedLanguage("cy", "Welsh", "Cymraeg"),
        SupportedLanguage("yi", "Yiddish", "ייִדיש"),
        SupportedLanguage("yo", "Yoruba", "Èdè Yorùbá")
    )

    fun getLanguageByCode(code: String): SupportedLanguage? {
        return ALL_SUPPORTED_LANGUAGES.firstOrNull { it.code.equals(code, ignoreCase = true) }
    }
}
